import mongoose from 'mongoose';
import dotenv from 'dotenv';
import dns from 'dns';

if (typeof dns.setDefaultResultOrder === 'function') {
  dns.setDefaultResultOrder('ipv4first');
}
import { User } from '../models/User';
import { College } from '../models/College';
import { Course } from '../models/Course';
import { Exam } from '../models/Exam';
import { Scholarship } from '../models/Scholarship';
import { Blog } from '../models/Blog';
import { Application } from '../models/Application';
import { SavedCollege } from '../models/SavedCollege';
import { ComparedCollege } from '../models/ComparedCollege';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/arunanandedtech';

const defaultCourses = [
  {
    name: 'B.Tech in Computer Science',
    category: 'Engineering',
    duration: '4 Years',
    eligibility: '10+2 with Physics, Chemistry, and Math (JEE qualified)',
    description: 'Undergraduate professional program in software engineering, algorithms, database systems, AI, and systems programming.',
    averageFees: '₹2.2 Lakhs / Year',
    careerOptions: ['Software Developer', 'System Architect', 'Data Scientist', 'DevOps Specialist'],
  },
  {
    name: 'MBA (PGP in Management)',
    category: 'Management',
    duration: '2 Years',
    eligibility: 'Bachelor Degree in any stream with minimum 50% marks (CAT qualified)',
    description: 'Postgraduate management program focusing on leadership, finance, operations, marketing, strategy, and organizational behavior.',
    averageFees: '₹11.5 Lakhs / Year',
    careerOptions: ['Management Consultant', 'Investment Analyst', 'Product Manager', 'HR Lead'],
  },
  {
    name: 'MBBS (Bachelor of Medicine)',
    category: 'Medicine',
    duration: '5.5 Years',
    eligibility: '10+2 with Physics, Chemistry, and Biology (NEET qualified)',
    description: 'Professional undergraduate degree in medical science, covering anatomy, pharmacology, clinical practice, and rotatory internship.',
    averageFees: '₹1.1 Lakhs / Year',
    careerOptions: ['General Physician', 'Resident Doctor', 'Clinical Researcher', 'Hospital Manager'],
  },
  {
    name: 'PGDM',
    category: 'Management',
    duration: '2 Years',
    eligibility: 'Graduate in any discipline (CAT/MAT/CMAT qualified)',
    description: 'Post Graduate Diploma in Management focusing on industry-relevant corporate training and business administration.',
    averageFees: '₹4.5 Lakhs / Year',
    careerOptions: ['Corporate Planner', 'Business Development Manager', 'Financial Controller'],
  },
  {
    name: 'BBA',
    category: 'Management',
    duration: '3 Years',
    eligibility: '10+2 from a recognized board with minimum 50% marks',
    description: 'Undergraduate program introducing core business management, human resources, marketing, and sales concepts.',
    averageFees: '₹1.5 Lakhs / Year',
    careerOptions: ['Sales Executive', 'Management Trainee', 'Marketing Assistant'],
  },
  {
    name: 'M.Tech in Artificial Intelligence',
    category: 'Engineering',
    duration: '2 Years',
    eligibility: 'B.Tech/B.E. in CSE/IT/ECE (GATE qualified)',
    description: 'Advanced postgraduate engineering specialization in machine learning, deep learning, NLP, computer vision, and neural systems.',
    averageFees: '₹80,000 / Year',
    careerOptions: ['AI Engineer', 'ML Researcher', 'CV Engineer', 'R&D Lead'],
  },
];

const defaultExams = [
  {
    examName: 'ATMA 2026',
    slug: 'atma',
    fullName: 'AIMS Test for Management Admissions',
    description: 'ATMA is a high-quality national level test recognized by AICTE for admissions to MBA and PGDM programs across India.',
    eligibility: 'Bachelor Degree with minimum 50% marks or equivalent from a recognized university.',
    applicationStartDate: new Date('2026-03-01'),
    applicationEndDate: new Date('2026-06-20'),
    examDate: new Date('2026-06-01'),
    resultDate: new Date('2026-07-12'),
    conductingBody: 'Association of Indian Management Schools (AIMS)',
    category: 'Management',
    mode: 'online' as const,
    courses: ['MBA', 'PGDM', 'BBA'],
    syllabus: [
      'Analytical Reasoning Skills (Part 1 & 2)',
      'Quantitative Skills (Part 1 & 2)',
      'Verbal Skills (Part 1 & 2)',
    ],
    pattern: '180 multiple-choice questions (MCQs) to be answered in 180 minutes.',
    difficulty: 'Medium',
  },
  {
    examName: 'CUET PG 2026',
    slug: 'cuet-pg',
    fullName: 'Common University Entrance Test (PG)',
    description: 'CUET PG provides a single-window opportunity for candidates seeking admission to various postgraduate programs in participating Central, State, and private universities.',
    eligibility: 'Graduate in any discipline from a recognized university. No age limit.',
    applicationStartDate: new Date('2026-01-15'),
    applicationEndDate: new Date('2026-04-25'),
    examDate: new Date('2026-06-13'),
    resultDate: new Date('2026-07-28'),
    conductingBody: 'National Testing Agency (NTA)',
    category: 'Management',
    mode: 'online' as const,
    courses: ['MBA', 'M.A.', 'M.Sc.', 'M.Com', 'BBA'],
    syllabus: [
      'Language Comprehension / Verbal Ability',
      'Mathematical / Quantitative Ability',
      'Data Interpretation & Logical Reasoning',
      'Domain Specific Knowledge',
    ],
    pattern: 'Computer-based test (CBT) with 75 multiple choice questions.',
    difficulty: 'Medium',
  },
  {
    examName: 'IBSAT 2025',
    slug: 'ibsat',
    fullName: 'ICFAI Business School (IBS) Aptitude Test or IBSAT',
    description: 'IBSAT is conducted by ICFAI Foundation for Higher Education for admission to the MBA/PGPM programs at all IBS campuses.',
    eligibility: 'Graduation in any discipline with 50% and above marks with English medium.',
    applicationStartDate: new Date('2025-07-01'),
    applicationEndDate: new Date('2025-12-21'),
    examDate: new Date('2025-12-27'),
    resultDate: new Date('2026-01-05'),
    conductingBody: 'ICFAI Foundation for Higher Education',
    category: 'Management',
    mode: 'online' as const,
    courses: ['MBA', 'PGPM', 'BBA'],
    syllabus: [
      'Verbal Ability',
      'Reading Comprehension',
      'Quantitative Aptitude',
      'Data Adequacy & Data Interpretation',
    ],
    pattern: 'Computer Based Test (CBT) containing 140 multiple choice questions with no negative marking.',
    difficulty: 'Medium',
  },
  {
    examName: 'CAT 2025',
    slug: 'cat',
    fullName: 'Common Admission Test (CAT)',
    description: 'Conducted annually by the IIMs on a rotational basis, CAT is the primary gateway to Indias top business schools, assessing quantitative, logical, and verbal capacity.',
    eligibility: 'Bachelor Degree with minimum 50% marks or equivalent CGPA.',
    applicationStartDate: new Date('2025-08-01'),
    applicationEndDate: new Date('2025-09-15'),
    examDate: new Date('2025-11-30'),
    resultDate: new Date('2026-01-05'),
    conductingBody: 'Indian Institutes of Management (IIMs)',
    category: 'Management',
    mode: 'online' as const,
    courses: ['MBA', 'PGDM'],
    syllabus: [
      'Verbal Ability & Reading Comprehension (VARC)',
      'Data Interpretation & Logical Reasoning (DILR)',
      'Quantitative Ability (QA)',
    ],
    pattern: '3 Sections, 2 hours total (40 minutes per section), mix of MCQs and Non-MCQs.',
    difficulty: 'Hard',
  },
  {
    examName: 'NPAT 2025',
    slug: 'npat',
    fullName: 'NMIMS NPAT Examination',
    description: 'NPAT is the official entrance test for admissions to Undergraduate Degree and Integrated Degree Programs offered by SVKM\'s NMIMS.',
    eligibility: '10+2 with minimum 50%-60% marks from a recognized board.',
    applicationStartDate: new Date('2025-02-01'),
    applicationEndDate: new Date('2025-05-20'),
    examDate: new Date('2025-06-01'),
    resultDate: new Date('2025-07-12'),
    conductingBody: 'SVKM\'s NMIMS',
    category: 'Management',
    mode: 'online' as const,
    courses: ['BBA', 'B.Com', 'B.Sc.'],
    syllabus: [
      'Quantitative & Numerical Ability',
      'Reasoning & General Intelligence',
      'Proficiency in English Language',
    ],
    pattern: '120-minute online exam with 120 questions, no negative marking.',
    difficulty: 'Medium',
  },
  {
    examName: 'PU CET 2025',
    slug: 'pu-cet',
    fullName: 'Punjab University Common Entrance Test',
    description: 'PU CET is conducted by Panjab University, Chandigarh, for admissions to various undergraduate courses in Science, Pharmacy, and allied disciplines.',
    eligibility: '10+2 examination with Physics, Chemistry, and Biology/Maths with 50% marks.',
    applicationStartDate: new Date('2025-04-01'),
    applicationEndDate: new Date('2025-05-20'),
    examDate: new Date('2025-06-15'),
    resultDate: new Date('2025-07-02'),
    conductingBody: 'Panjab University, Chandigarh',
    category: 'Agriculture',
    mode: 'offline' as const,
    courses: ['B.Sc.', 'B.Pharma'],
    syllabus: [
      'Physics: Kinematics, Laws of Motion, Optics',
      'Chemistry: Atom structure, Organic, Thermodynamics',
      'Biology / Mathematics: Botany, Zoology, Calculus, Algebra',
    ],
    pattern: 'Offline pen-paper test containing objective questions, 70 minutes per subject paper.',
    difficulty: 'Medium',
  },
  {
    examName: 'WBJEE 2025',
    slug: 'wbjee',
    fullName: 'West Bengal Joint Entrance Examinations',
    description: 'WBJEE is a state-level exam conducted for admission to Government and private Engineering, Technology, Pharmacy, and Architecture colleges in West Bengal.',
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/Biology/Biotech with 45% aggregate.',
    applicationStartDate: new Date('2024-12-20'),
    applicationEndDate: new Date('2025-02-05'),
    examDate: new Date('2025-04-27'),
    resultDate: new Date('2025-05-15'),
    conductingBody: 'West Bengal Joint Entrance Examinations Board',
    category: 'Engineering',
    mode: 'offline' as const,
    courses: ['B.Tech', 'B.Arch', 'B.Pharma'],
    syllabus: [
      'Mathematics: Coordinate Geometry, Calculus, Algebra',
      'Physics: Mechanics, Electrostatics, Thermal Physics',
      'Chemistry: Physical, Inorganic, Organic Chemistry',
    ],
    pattern: 'OMR based offline exam with two papers: Paper-I (Maths) and Paper-II (Physics & Chemistry).',
    difficulty: 'Hard',
  },
  {
    examName: 'CLAT 2025',
    slug: 'clat',
    fullName: 'Common Law Admission Test',
    description: 'CLAT is a centralized test for admissions to 24 National Law Universities in India, testing analytical reading, comprehension, and legal logical skills.',
    eligibility: '10+2 or equivalent with minimum 45% marks.',
    applicationStartDate: new Date('2024-07-01'),
    applicationEndDate: new Date('2024-11-10'),
    examDate: new Date('2024-12-01'),
    resultDate: new Date('2024-12-15'),
    conductingBody: 'Consortium of National Law Universities',
    category: 'Law',
    mode: 'offline' as const,
    courses: ['Allied', 'LLB', 'LLM'],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs including General Knowledge',
      'Legal Reasoning & Aptitude',
      'Logical Reasoning',
      'Quantitative Techniques',
    ],
    pattern: '2-hour offline pen-and-paper test with 120 comprehension-based MCQs.',
    difficulty: 'Medium to Hard',
  },
  {
    examName: 'MAT 2025',
    slug: 'mat',
    fullName: 'Management Aptitude Test (MAT)',
    description: 'MAT is a national level management entrance test conducted by AIMA multiple times a year for admissions to over 600 business schools in India.',
    eligibility: 'Graduate in any discipline. Candidates in final year of graduation can also apply.',
    applicationStartDate: new Date('2025-01-01'),
    applicationEndDate: new Date('2025-02-15'),
    examDate: new Date('2025-03-10'),
    resultDate: new Date('2025-03-31'),
    conductingBody: 'All India Management Association (AIMA)',
    category: 'Management',
    mode: 'both' as const,
    courses: ['MBA', 'PGDM', 'BBA'],
    syllabus: [
      'Language Comprehension',
      'Mathematical Skills',
      'Data Analysis and Sufficiency',
      'Intelligence and Critical Reasoning',
      'Indian and Global Environment',
    ],
    pattern: 'Available in CBT, PBT, and IBT modes. 150 questions in 120 minutes.',
    difficulty: 'Medium',
  },
  {
    examName: 'XAT 2025',
    slug: 'xat',
    fullName: 'Xavier Aptitude Test Exam',
    description: 'XAT is conducted by XLRI Jamshedpur on behalf of XAMI. It is widely considered one of the most comprehensive aptitude tests for management admissions.',
    eligibility: 'Bachelor Degree in any discipline from a recognized university.',
    applicationStartDate: new Date('2024-08-15'),
    applicationEndDate: new Date('2024-11-30'),
    examDate: new Date('2025-01-05'),
    resultDate: new Date('2025-01-20'),
    conductingBody: 'XLRI Jamshedpur',
    category: 'Management',
    mode: 'online' as const,
    courses: ['MBA', 'PGDM'],
    syllabus: [
      'Decision Making',
      'Verbal and Logical Ability',
      'Quantitative Ability & Data Interpretation',
      'General Knowledge',
    ],
    pattern: 'Online test with 100 questions of MCQ type and one analytical essay topic.',
    difficulty: 'Hard',
  },
  {
    examName: 'CMAT 2026',
    slug: 'cmat',
    fullName: 'Common Management Admission Test (CMAT)',
    description: 'CMAT is a national-level entrance exam conducted by NTA for admission to management programs in AICTE-approved institutions.',
    eligibility: 'Graduate in any discipline from a recognized institution.',
    applicationStartDate: new Date('2026-02-01'),
    applicationEndDate: new Date('2026-03-15'),
    examDate: new Date('2026-05-15'),
    resultDate: new Date('2026-06-05'),
    conductingBody: 'National Testing Agency (NTA)',
    category: 'Management',
    mode: 'online' as const,
    courses: ['MBA', 'PGDM'],
    syllabus: [
      'Quantitative Techniques & Data Interpretation',
      'Logical Reasoning',
      'Language Comprehension',
      'General Awareness',
      'Innovation & Entrepreneurship',
    ],
    pattern: 'Computer Based Test (CBT) with 100 multiple choice questions.',
    difficulty: 'Medium',
  },
  {
    examName: 'SNAP Exam',
    slug: 'snap',
    fullName: 'Symbiosis National Aptitude Test (SNAP)',
    description: 'SNAP is a common written test for candidates seeking admission to any post-graduate management programs offered by Symbiosis International University.',
    eligibility: 'Graduate from any recognized university with a minimum of 50% marks.',
    applicationStartDate: new Date('2025-08-20'),
    applicationEndDate: new Date('2025-11-20'),
    examDate: new Date('2025-12-10'),
    resultDate: new Date('2026-01-10'),
    conductingBody: 'Symbiosis International University',
    category: 'Management',
    mode: 'online' as const,
    courses: ['MBA', 'M.Sc.'],
    syllabus: [
      'General English: Reading Comprehension, Verbal Ability',
      'Analytical & Logical Reasoning',
      'Quantitative, Data Interpretation & Data Sufficiency',
    ],
    pattern: '60-minute CBT with 60 questions, negative marking of 0.25 for incorrect answers.',
    difficulty: 'Medium',
  },

  // ==========================================
  // ENGINEERING NEW EXAMS
  // ==========================================
  {
    examName: 'JEE Main 2026',
    slug: 'jee-main',
    fullName: 'Joint Entrance Examination (Main)',
    description: 'JEE Main is the premier national-level engineering entrance exam for NITs, IIITs, and other Centrally Funded Technical Institutions.',
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/Biology/Biotech.',
    applicationStartDate: new Date('2026-01-10'),
    applicationEndDate: new Date('2026-03-02'),
    examDate: new Date('2026-04-15'),
    resultDate: new Date('2026-05-10'),
    conductingBody: 'National Testing Agency (NTA)',
    category: 'Engineering',
    mode: 'online' as const,
    courses: ['B.Tech', 'B.Arch', 'Allied'],
    syllabus: ['Mathematics', 'Physics', 'Chemistry'],
    pattern: 'MCQs and Numerical Value Questions, 3 hours.',
    difficulty: 'Hard',
  },
  {
    examName: 'JEE Advanced 2026',
    slug: 'jee-advanced',
    fullName: 'Joint Entrance Examination (Advanced)',
    description: 'JEE Advanced is the sole gateway for admission to the undergraduate programs of the Indian Institutes of Technology (IITs).',
    eligibility: 'Must qualify JEE Main and be within the top 2,50,000 candidates.',
    applicationStartDate: new Date('2026-04-26'),
    applicationEndDate: new Date('2026-05-05'),
    examDate: new Date('2026-05-24'),
    resultDate: new Date('2026-06-15'),
    conductingBody: 'Indian Institute of Technology (IIT) Delhi',
    category: 'Engineering',
    mode: 'online' as const,
    courses: ['B.Tech', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'Mathematics (Advanced topics)'],
    pattern: 'Two papers of 3 hours each, testing analytical and comprehension abilities.',
    difficulty: 'Hard',
  },
  {
    examName: 'GATE 2026',
    slug: 'gate',
    fullName: 'Graduate Aptitude Test in Engineering',
    description: 'GATE is a highly competitive examination testing comprehensive understanding of undergraduate engineering and science subjects.',
    eligibility: 'Bachelor\'s degree in Engineering/Technology/Architecture/Science/Arts.',
    applicationStartDate: new Date('2025-08-30'),
    applicationEndDate: new Date('2025-10-15'),
    examDate: new Date('2026-02-07'),
    resultDate: new Date('2026-03-15'),
    conductingBody: 'Indian Institute of Science (IISc) Bangalore',
    category: 'Engineering',
    mode: 'online' as const,
    courses: ['B.Tech', 'Allied'],
    syllabus: ['General Aptitude', 'Engineering Mathematics', 'Technical Subject paper'],
    pattern: '65 questions (MCQs, MSQs, and NATs) in 180 minutes.',
    difficulty: 'Hard',
  },
  {
    examName: 'BITSAT 2026',
    slug: 'bitsat',
    fullName: 'BITS Admission Test',
    description: 'BITSAT is conducted by BITS Pilani for admission to integrated first-degree programs at its Pilani, Goa, and Hyderabad campuses.',
    eligibility: '10+2 with Physics, Chemistry, and Mathematics/Biology with 75% marks.',
    applicationStartDate: new Date('2026-01-15'),
    applicationEndDate: new Date('2026-04-12'),
    examDate: new Date('2026-05-20'),
    resultDate: new Date('2026-06-05'),
    conductingBody: 'Birla Institute of Technology and Science (BITS) Pilani',
    category: 'Engineering',
    mode: 'online' as const,
    courses: ['B.Tech', 'B.Sc.', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'English Proficiency & Logical Reasoning', 'Mathematics/Biology'],
    pattern: '130 questions to be answered in 3 hours. Features extra questions for fast candidates.',
    difficulty: 'Medium to Hard',
  },
  {
    examName: 'SRMJEEE 2026',
    slug: 'srmjeee',
    fullName: 'SRM Joint Engineering Entrance Exam',
    description: 'SRMJEEE is conducted by SRM Institute of Science and Technology for admissions to B.Tech programs across all campuses.',
    eligibility: '10+2 with minimum 60% marks in Physics, Chemistry, and Mathematics.',
    applicationStartDate: new Date('2026-01-05'),
    applicationEndDate: new Date('2026-04-10'),
    examDate: new Date('2026-04-20'),
    resultDate: new Date('2026-05-02'),
    conductingBody: 'SRM Institute of Science and Technology',
    category: 'Engineering',
    mode: 'online' as const,
    courses: ['B.Tech'],
    syllabus: ['Physics', 'Chemistry', 'Mathematics', 'English & Aptitude'],
    pattern: '125 MCQs to be answered in 2.5 hours with no negative marking.',
    difficulty: 'Medium',
  },
  {
    examName: 'IPU CET BCA 2026',
    slug: 'ipu-cet-bca',
    fullName: 'Indraprastha University Common Entrance Test (BCA)',
    description: 'Conducted by GGSIPU Delhi for undergraduate computer application course placements.',
    eligibility: '10+2 with English and Mathematics/Computer Science/IP with 50% marks.',
    applicationStartDate: new Date('2026-02-01'),
    applicationEndDate: new Date('2026-04-15'),
    examDate: new Date('2026-05-18'),
    resultDate: new Date('2026-06-02'),
    conductingBody: 'Guru Gobind Singh Indraprastha University (GGSIPU)',
    category: 'Engineering',
    mode: 'offline' as const,
    courses: ['BCA', 'Allied'],
    syllabus: ['English Language', 'Mathematics', 'Computer Awareness', 'General Knowledge'],
    pattern: '100 MCQs in 150 minutes, standard offline pen and paper exam.',
    difficulty: 'Medium',
  },
  {
    examName: 'NIMCET 2026',
    slug: 'nimcet',
    fullName: 'NIT MCA Common Entrance Test',
    description: 'NIMCET is the national level entrance test for admission into MCA programs across participating National Institutes of Technology.',
    eligibility: 'B.Sc. / B.Sc. (Hons) / BCA / BIT with Mathematics/Statistics as one subject.',
    applicationStartDate: new Date('2026-03-01'),
    applicationEndDate: new Date('2026-04-20'),
    examDate: new Date('2026-06-08'),
    resultDate: new Date('2026-06-25'),
    conductingBody: 'National Institute of Technology (NIT) Jamshedpur',
    category: 'Engineering',
    mode: 'online' as const,
    courses: ['BCA', 'Allied'],
    syllabus: ['Mathematics (600 marks)', 'Analytical Ability & Logical Reasoning', 'Computer Awareness', 'General English'],
    pattern: '120 MCQs in 120 minutes with a negative marking scheme.',
    difficulty: 'Hard',
  },
  {
    examName: 'Christ University BCA 2026',
    slug: 'christ-bca',
    fullName: 'Christ University Entrance Test (BCA)',
    description: 'Christ University entrance exam for the prestigious Bachelor of Computer Applications program in Bangalore.',
    eligibility: '10+2 from any recognized board in India.',
    applicationStartDate: new Date('2026-01-10'),
    applicationEndDate: new Date('2026-04-05'),
    examDate: new Date('2026-04-14'),
    resultDate: new Date('2026-04-22'),
    conductingBody: 'Christ University Bangalore',
    category: 'Engineering',
    mode: 'online' as const,
    courses: ['BCA'],
    syllabus: ['Fundamental Accounting', 'English', 'Mathematics', 'Logical Reasoning', 'Data Analysis'],
    pattern: 'Computer-based online entrance test followed by personal interview and micro-presentation.',
    difficulty: 'Medium',
  },

  // ==========================================
  // COMMERCE NEW EXAMS
  // ==========================================
  {
    examName: 'CA Foundation 2026',
    slug: 'ca-foundation',
    fullName: 'Chartered Accountants Foundation Examination',
    description: 'CA Foundation is the entry-level exam for the Chartered Accountancy course conducted by ICAI.',
    eligibility: 'Must have registered with Board of Studies of ICAI and passed 10+2.',
    applicationStartDate: new Date('2026-01-01'),
    applicationEndDate: new Date('2026-02-01'),
    examDate: new Date('2026-06-20'),
    resultDate: new Date('2026-08-10'),
    conductingBody: 'Institute of Chartered Accountants of India (ICAI)',
    category: 'Commerce',
    mode: 'offline' as const,
    courses: ['B.Com', 'Allied'],
    syllabus: ['Principles and Practice of Accounting', 'Business Laws', 'Quantitative Aptitude', 'Business Economics'],
    pattern: '4 papers (2 subjective of 100 marks each, 2 objective with negative marking).',
    difficulty: 'Hard',
  },
  {
    examName: 'CSEET 2026',
    slug: 'cseet',
    fullName: 'Company Secretary Executive Entrance Test',
    description: 'CSEET is the mandatory entrance test conducted by ICSI for admission to the Company Secretary Executive Program.',
    eligibility: 'Must have passed or appearing in 10+2 or equivalent examination.',
    applicationStartDate: new Date('2026-02-15'),
    applicationEndDate: new Date('2026-04-15'),
    examDate: new Date('2026-05-09'),
    resultDate: new Date('2026-05-20'),
    conductingBody: 'Institute of Company Secretaries of India (ICSI)',
    category: 'Commerce',
    mode: 'online' as const,
    courses: ['B.Com', 'Allied'],
    syllabus: ['Business Communication', 'Legal Aptitude & Logical Reasoning', 'Economic & Business Environment', 'Current Affairs'],
    pattern: 'Computer-based exam of 120 minutes containing 140 questions with no negative marking.',
    difficulty: 'Medium',
  },
  {
    examName: 'CMA Foundation 2026',
    slug: 'cma-foundation',
    fullName: 'Cost and Management Accountants Foundation',
    description: 'CMA Foundation is conducted by the Institute of Cost Accountants of India (ICMAI) as the gateway to the CMA course.',
    eligibility: '10+2 from a recognized board or equivalent.',
    applicationStartDate: new Date('2026-01-05'),
    applicationEndDate: new Date('2026-02-10'),
    examDate: new Date('2026-06-10'),
    resultDate: new Date('2026-07-05'),
    conductingBody: 'Institute of Cost Accountants of India (ICMAI)',
    category: 'Commerce',
    mode: 'online' as const,
    courses: ['B.Com', 'Allied'],
    syllabus: ['Fundamentals of Economics and Management', 'Fundamentals of Financial and Cost Accounting', 'Fundamentals of Laws and Ethics', 'Fundamentals of Business Mathematics and Statistics'],
    pattern: 'Online exam with Multiple Choice Questions across 4 papers.',
    difficulty: 'Medium',
  },
  {
    examName: 'CUET UG Commerce 2026',
    slug: 'cuet-ug-commerce',
    fullName: 'Common University Entrance Test (UG - Commerce)',
    description: 'CUET UG provides a common platform for admission to undergraduate programs in Central Universities across India.',
    eligibility: 'Must have passed 10+2 from a recognized education board.',
    applicationStartDate: new Date('2026-02-09'),
    applicationEndDate: new Date('2026-03-25'),
    examDate: new Date('2026-05-20'),
    resultDate: new Date('2026-07-02'),
    conductingBody: 'National Testing Agency (NTA)',
    category: 'Commerce',
    mode: 'both' as const,
    courses: ['B.Com', 'Allied'],
    syllabus: ['Accountancy / Book Keeping', 'Business Studies', 'Economics / Business Economics', 'English Language'],
    pattern: 'Computer-based test (CBT) with section-wise objective type multiple choice questions.',
    difficulty: 'Medium',
  },

  // ==========================================
  // LAW NEW EXAMS
  // ==========================================
  {
    examName: 'AILET 2026',
    slug: 'ailet',
    fullName: 'All India Law Entrance Test',
    description: 'AILET is conducted by National Law University Delhi (NLU Delhi) for admissions to BA LLB (Hons), LLM, and Ph.D. programs.',
    eligibility: '10+2 with 45% marks (40% for SC/ST/PwD). No upper age limit.',
    applicationStartDate: new Date('2025-08-01'),
    applicationEndDate: new Date('2025-11-15'),
    examDate: new Date('2025-12-07'),
    resultDate: new Date('2025-12-25'),
    conductingBody: 'National Law University Delhi',
    category: 'Law',
    mode: 'offline' as const,
    courses: ['Allied', 'B.A.', 'LLB'],
    syllabus: ['English Language', 'Current Affairs & General Knowledge', 'Logical Reasoning'],
    pattern: '150 questions to be solved in 120 minutes with a negative marking of 0.25.',
    difficulty: 'Hard',
  },
  {
    examName: 'LSAT India 2026',
    slug: 'lsat-india',
    fullName: 'Law School Admission Test - India',
    description: 'LSAT India is a standardized test of reading and verbal reasoning skills, used by several premier private law colleges in India.',
    eligibility: '10+2 from a recognized board for 5-year integrated law, or graduation for 3-year LLB.',
    applicationStartDate: new Date('2025-11-10'),
    applicationEndDate: new Date('2026-05-02'),
    examDate: new Date('2026-05-16'),
    resultDate: new Date('2026-06-12'),
    conductingBody: 'Law School Admission Council (LSAC)',
    category: 'Law',
    mode: 'online' as const,
    courses: ['Allied', 'LLB'],
    syllabus: ['Analytical Reasoning', 'Logical Reasoning (Part 1 & 2)', 'Reading Comprehension'],
    pattern: '92 questions in 2 hours and 20 minutes across 4 timed sections, no negative marking.',
    difficulty: 'Medium to Hard',
  },
  {
    examName: 'MH CET Law 2026',
    slug: 'mhcet-law',
    fullName: 'Maharashtra Common Entrance Test for Law',
    description: 'State-level examination conducted by the State Common Entrance Test Cell, Maharashtra, for admissions to law courses.',
    eligibility: '10+2 with 45% aggregate (40% for MH SC/ST) for 5-year Integrated LLB.',
    applicationStartDate: new Date('2026-01-10'),
    applicationEndDate: new Date('2026-02-18'),
    examDate: new Date('2026-03-28'),
    resultDate: new Date('2026-04-30'),
    conductingBody: 'State Common Entrance Test Cell, Maharashtra',
    category: 'Law',
    mode: 'online' as const,
    courses: ['Allied', 'B.A.', 'LLB'],
    syllabus: ['Legal Aptitude and Legal Reasoning', 'General Knowledge with Current Affairs', 'Logical and Analytical Reasoning', 'English', 'Mathematical Ability'],
    pattern: '150 objective questions in 120 minutes with no negative marking.',
    difficulty: 'Medium',
  },
  {
    examName: 'SLAT 2026',
    slug: 'slat',
    fullName: 'Symbiosis Law Admission Test',
    description: 'Symbiosis Law Admission Test (SLAT) is the common entrance test for admission to BA LLB and BBA LLB programs in Symbiosis Law Schools.',
    eligibility: '10+2 or equivalent or 10+3 Diploma with minimum 45% marks from any recognized board.',
    applicationStartDate: new Date('2026-01-10'),
    applicationEndDate: new Date('2026-04-12'),
    examDate: new Date('2026-05-05'),
    resultDate: new Date('2026-05-15'),
    conductingBody: 'Symbiosis International University (SIU)',
    category: 'Law',
    mode: 'online' as const,
    courses: ['Allied', 'LLB'],
    syllabus: ['Logical Reasoning', 'Legal Reasoning', 'Analytical Reasoning', 'Reading Comprehension', 'General Knowledge'],
    pattern: '60 MCQs in 60 minutes, followed by Writing Ability Test (WAT) and Personal Interaction (PI).',
    difficulty: 'Medium',
  },

  // ==========================================
  // ARTS NEW EXAMS
  // ==========================================
  {
    examName: 'CUET UG Arts 2026',
    slug: 'cuet-ug-arts',
    fullName: 'Common University Entrance Test (UG - Arts)',
    description: 'Gateway for admission to Bachelor of Arts (BA Hons) and other humanities courses in premium Central Universities.',
    eligibility: '10+2 from a recognized board in any stream.',
    applicationStartDate: new Date('2026-02-09'),
    applicationEndDate: new Date('2026-03-25'),
    examDate: new Date('2026-05-22'),
    resultDate: new Date('2026-07-02'),
    conductingBody: 'National Testing Agency (NTA)',
    category: 'Arts',
    mode: 'both' as const,
    courses: ['B.A.', 'Allied'],
    syllabus: ['English Language', 'History', 'Political Science', 'Sociology / Geography', 'General Test'],
    pattern: 'Computer-based test containing multi-choice objective sections.',
    difficulty: 'Medium',
  },
  {
    examName: 'TISSNET 2026',
    slug: 'tissnet',
    fullName: 'Tata Institute of Social Sciences NET',
    description: 'TISSNET is conducted for admissions to Master of Arts and other postgraduate social work programs of TISS campuses.',
    eligibility: 'Bachelor\'s degree of minimum 3 or 4 years duration or equivalent from a recognized university.',
    applicationStartDate: new Date('2025-10-15'),
    applicationEndDate: new Date('2025-11-30'),
    examDate: new Date('2026-01-10'),
    resultDate: new Date('2026-02-15'),
    conductingBody: 'Tata Institute of Social Sciences (TISS)',
    category: 'Arts',
    mode: 'online' as const,
    courses: ['B.A.', 'Allied'],
    syllabus: ['General Awareness', 'Mathematical & Logical Reasoning', 'English Proficiency'],
    pattern: '100 multiple choice questions to be answered in 100 minutes, with no negative marking.',
    difficulty: 'Medium to Hard',
  },
  {
    examName: 'PUBDET 2026',
    slug: 'pubdet',
    fullName: 'Presidency University Bachelor Degree Entrance Test',
    description: 'PUBDET is conducted by WBJEEB for admission to three-year B.A. and B.Sc. Honors programs at Presidency University, Kolkata.',
    eligibility: '10+2 from a recognized board with minimum aggregate requirements based on subject selection.',
    applicationStartDate: new Date('2026-02-10'),
    applicationEndDate: new Date('2026-03-18'),
    examDate: new Date('2026-06-21'),
    resultDate: new Date('2026-07-15'),
    conductingBody: 'West Bengal Joint Entrance Examinations Board (WBJEEB)',
    category: 'Arts',
    mode: 'offline' as const,
    courses: ['B.A.', 'B.Sc.'],
    syllabus: ['Subject specific syllabus (English, History, Sociology, Economics, etc.)'],
    pattern: 'OMR based offline exam with 50 MCQs to be answered in 90 minutes.',
    difficulty: 'Medium',
  },
  {
    examName: 'HSEE 2026',
    slug: 'hsee',
    fullName: 'Humanities and Social Sciences Entrance Examination',
    description: 'Conducted by IIT Madras for admissions to its integrated five-year Master of Arts (M.A.) program.',
    eligibility: '10+2 with minimum 60% aggregate marks (55% for SC/ST/PD) from a recognized board.',
    applicationStartDate: new Date('2026-03-01'),
    applicationEndDate: new Date('2026-04-15'),
    examDate: new Date('2026-06-07'),
    resultDate: new Date('2026-06-28'),
    conductingBody: 'Indian Institute of Technology (IIT) Madras',
    category: 'Arts',
    mode: 'online' as const,
    courses: ['B.A.', 'Allied'],
    syllabus: ['English, Analytical & Quantitative Ability', 'General Studies (Indian Economy, Society, World Affairs)'],
    pattern: 'Part I: 150-minute computer test, Part II: 30-minute essay writing section.',
    difficulty: 'Hard',
  },
  {
    examName: 'RIE CEE B.Ed 2026',
    slug: 'rie-cee',
    fullName: 'Regional Institute of Education Common Entrance Exam',
    description: 'National level entrance examination conducted by NCERT for admission to various teacher education programs (B.Ed, B.A. B.Ed, B.Sc. B.Ed).',
    eligibility: 'Must hold a graduation or post-graduation degree in Science/Social Sciences/Humanities with 50% marks.',
    applicationStartDate: new Date('2026-04-10'),
    applicationEndDate: new Date('2026-05-10'),
    examDate: new Date('2026-06-14'),
    resultDate: new Date('2026-07-05'),
    conductingBody: 'National Council of Educational Research and Training (NCERT)',
    category: 'Arts',
    mode: 'offline' as const,
    courses: ['B.Ed'],
    syllabus: ['Language Proficiency in English', 'Teaching Aptitude / Attitude', 'Reasoning Ability'],
    pattern: '80 MCQs in 120 minutes with a negative marking of 0.25.',
    difficulty: 'Medium',
  },
  {
    examName: 'DU B.Ed 2026',
    slug: 'du-bed',
    fullName: 'Delhi University Bachelor of Education Entrance',
    description: 'Admissions gateway for the prestigious B.Ed program offered by Faculty of Education under the University of Delhi.',
    eligibility: 'Bachelor\'s Degree and/or Master\'s Degree in Science/Social Sciences/Humanities with 50% marks.',
    applicationStartDate: new Date('2026-02-15'),
    applicationEndDate: new Date('2026-04-05'),
    examDate: new Date('2026-05-28'),
    resultDate: new Date('2026-06-20'),
    conductingBody: 'University of Delhi (Faculty of Education)',
    category: 'Arts',
    mode: 'online' as const,
    courses: ['B.Ed'],
    syllabus: ['Subject Knowledge (up to Class X)', 'Language Proficiency (English/Hindi)', 'Reasoning & General Awareness'],
    pattern: '100 MCQs in 120 minutes, conducted through CUET PG guidelines.',
    difficulty: 'Medium',
  },
  {
    examName: 'BHU B.Ed 2026',
    slug: 'bhu-bed',
    fullName: 'Banaras Hindu University B.Ed Admission Test',
    description: 'BHU B.Ed entrance is conducted by NTA under CUET PG, for teacher training admissions in Faculty of Education, BHU.',
    eligibility: '50% marks in Bachelor degree and/or Master degree in Science, Social Science, Humanities.',
    applicationStartDate: new Date('2026-02-15'),
    applicationEndDate: new Date('2026-04-10'),
    examDate: new Date('2026-05-30'),
    resultDate: new Date('2026-06-25'),
    conductingBody: 'Banaras Hindu University (NTA)',
    category: 'Arts',
    mode: 'online' as const,
    courses: ['B.Ed'],
    syllabus: ['Teaching Aptitude', 'Reasoning, General Awareness', 'Subject Group Knowledge (Languages/Science/Maths/Social Sciences)'],
    pattern: 'Computer-based test of 100 questions, total duration 120 minutes.',
    difficulty: 'Medium',
  },

  // ==========================================
  // ARCHITECTURE NEW EXAMS
  // ==========================================
  {
    examName: 'NATA 2026',
    slug: 'nata',
    fullName: 'National Aptitude Test in Architecture',
    description: 'NATA is conducted by the Council of Architecture (CoA) for admission to the first year of 5-year B.Arch degree courses in India.',
    eligibility: 'Passed 10+2 with Physics, Chemistry & Mathematics, or 10+3 Diploma with Mathematics.',
    applicationStartDate: new Date('2026-02-01'),
    applicationEndDate: new Date('2026-03-20'),
    examDate: new Date('2026-04-06'),
    resultDate: new Date('2026-04-20'),
    conductingBody: 'Council of Architecture (CoA)',
    category: 'Architecture',
    mode: 'online' as const,
    courses: ['Allied', 'B.Arch'],
    syllabus: ['Drawing and Visual Composition', 'Cognitive Skills', 'Mathematics & General Aptitude'],
    pattern: 'Computer-based test containing MCQ, MSQ, PCQ, and numerical questions, 180 minutes.',
    difficulty: 'Medium',
  },
  {
    examName: 'JEE Main Paper 2 2026',
    slug: 'jee-main-paper2',
    fullName: 'Joint Entrance Examination (Paper 2)',
    description: 'JEE Main Paper 2 is the gateway for admissions to B.Arch and B.Plan courses offered by SPAs, NITs, and select CFTIs.',
    eligibility: '10+2 with Physics, Chemistry, and Mathematics (minimum 50% marks).',
    applicationStartDate: new Date('2026-01-10'),
    applicationEndDate: new Date('2026-03-02'),
    examDate: new Date('2026-04-18'),
    resultDate: new Date('2026-05-15'),
    conductingBody: 'National Testing Agency (NTA)',
    category: 'Architecture',
    mode: 'online' as const,
    courses: ['Allied', 'B.Arch'],
    syllabus: ['Mathematics (Part I)', 'Aptitude Test (Part II)', 'Drawing Test (Part III - Pen and Paper)'],
    pattern: 'Mixed Computer-based (Maths & Aptitude) and offline (Drawing) test, 3 hours.',
    difficulty: 'Hard',
  },
  {
    examName: 'AAT 2026',
    slug: 'aat',
    fullName: 'Architecture Aptitude Test',
    description: 'AAT is the entrance test for candidates seeking admission to the 5-year Bachelor of Architecture (B.Arch) program at IIT Roorkee, IIT Kharagpur, and IIT BHU.',
    eligibility: 'Must have qualified JEE Advanced 2026 and registered for AAT.',
    applicationStartDate: new Date('2026-06-02'),
    applicationEndDate: new Date('2026-06-08'),
    examDate: new Date('2026-06-12'),
    resultDate: new Date('2026-06-18'),
    conductingBody: 'Joint Admission Board (JAB) / IITs',
    category: 'Architecture',
    mode: 'offline' as const,
    courses: ['Allied', 'B.Arch'],
    syllabus: ['Freehand Drawing', 'Geometrical Drawing', 'Three-Dimensional Perception', 'Imagination and Aesthetic Sensitivity'],
    pattern: '3-hour pen and paper drawing examination held only at IIT campuses.',
    difficulty: 'Hard',
  },

  // ==========================================
  // DENTAL NEW EXAMS
  // ==========================================
  {
    examName: 'NEET MDS 2026',
    slug: 'neet-mds',
    fullName: 'National Eligibility cum Entrance Test for MDS',
    description: 'NEET MDS is the single entrance exam for admission to various Post Graduate MDS courses under the Dentists Act.',
    eligibility: 'BDS degree from a recognized university and completion of 1-year rotatory internship.',
    applicationStartDate: new Date('2025-12-15'),
    applicationEndDate: new Date('2026-01-25'),
    examDate: new Date('2026-03-08'),
    resultDate: new Date('2026-04-02'),
    conductingBody: 'National Board of Examinations (NBE)',
    category: 'Dental',
    mode: 'online' as const,
    courses: ['BDS', 'Allied'],
    syllabus: ['General Anatomy', 'Dental Anatomy', 'Oral Pathology', 'Orthodontics', 'Periodontics', 'Prosthodontics'],
    pattern: '240 multiple-choice questions (MCQs) in English, 3 hours duration.',
    difficulty: 'Hard',
  },
  {
    examName: 'NEET UG Dental 2026',
    slug: 'neet-ug-dental',
    fullName: 'National Eligibility cum Entrance Test (UG) for BDS',
    description: 'NEET UG is the highly competitive national-level entrance exam for securing Bachelor of Dental Surgery (BDS) seats in India.',
    eligibility: '10+2 with Physics, Chemistry, Biology/Biotech, and English with 50% aggregate.',
    applicationStartDate: new Date('2026-02-09'),
    applicationEndDate: new Date('2026-03-10'),
    examDate: new Date('2026-05-03'),
    resultDate: new Date('2026-06-15'),
    conductingBody: 'National Testing Agency (NTA)',
    category: 'Dental',
    mode: 'offline' as const,
    courses: ['BDS', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'Biology (Botany & Zoology)'],
    pattern: '180 objective questions (out of 200) to be solved in 200 minutes on OMR sheet.',
    difficulty: 'Hard',
  },
  {
    examName: 'AIIMS Dental 2026',
    slug: 'aiims-dental',
    fullName: 'AIIMS Bachelor of Dental Surgery Entrance',
    description: 'AIIMS Dental entrance is conducted for admissions to BDS seats at select All India Institutes of Medical Sciences.',
    eligibility: '10+2 with Physics, Chemistry, Biology and English with 60% aggregate.',
    applicationStartDate: new Date('2026-02-15'),
    applicationEndDate: new Date('2026-04-12'),
    examDate: new Date('2026-06-01'),
    resultDate: new Date('2026-06-18'),
    conductingBody: 'All India Institute of Medical Sciences (AIIMS)',
    category: 'Dental',
    mode: 'online' as const,
    courses: ['BDS', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'Biology', 'General Knowledge / Aptitude'],
    pattern: 'Computer Based Test with multiple-choice questions.',
    difficulty: 'Hard',
  },
  {
    examName: 'JIPMER Dental 2026',
    slug: 'jipmer-dental',
    fullName: 'JIPMER BDS Entrance Cycle',
    description: 'JIPMER dental entrance admission process for Bachelor of Dental Surgery seats.',
    eligibility: 'Passed 10+2 with Physics, Chemistry, Biology/Biotech and English with 50% marks.',
    applicationStartDate: new Date('2026-02-10'),
    applicationEndDate: new Date('2026-03-15'),
    examDate: new Date('2026-05-10'),
    resultDate: new Date('2026-06-10'),
    conductingBody: 'Jawaharlal Institute of Postgraduate Medical Education & Research',
    category: 'Dental',
    mode: 'online' as const,
    courses: ['BDS', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'Biology', 'English Language and Comprehension', 'Logical and Quantitative Reasoning'],
    pattern: 'Computer-based test of 200 questions, 150 minutes duration.',
    difficulty: 'Medium to Hard',
  },

  // ==========================================
  // AGRICULTURE NEW EXAMS
  // ==========================================
  {
    examName: 'ICAR AIEEA 2026',
    slug: 'icar-aieea',
    fullName: 'ICAR All India Entrance Examination for Admission',
    description: 'ICAR AIEEA UG is the national-level exam for admission to bachelor degree programmes in agriculture and allied sciences in agricultural universities.',
    eligibility: 'Passed 10+2 with PCM/PCB/PCMB/Agriculture with 50% marks in aggregate.',
    applicationStartDate: new Date('2026-02-15'),
    applicationEndDate: new Date('2026-04-02'),
    examDate: new Date('2026-05-15'),
    resultDate: new Date('2026-06-15'),
    conductingBody: 'National Testing Agency (NTA) / ICAR',
    category: 'Agriculture',
    mode: 'online' as const,
    courses: ['B.Sc.', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'Mathematics/Biology/Agriculture'],
    pattern: 'Computer Based Test (CBT) with 150 objective questions, 150 minutes duration.',
    difficulty: 'Medium',
  },
  {
    examName: 'MP PAT 2026',
    slug: 'mp-pat',
    fullName: 'Madhya Pradesh Pre-Agriculture Test',
    description: 'MP PAT is a state-level entrance test conducted by Vyapam for admission to B.Sc. (Agriculture) and B.Sc. (Forestry) courses in Madhya Pradesh.',
    eligibility: '10+2 in Science (PCB/PCM) or Agriculture from a recognized board.',
    applicationStartDate: new Date('2026-04-01'),
    applicationEndDate: new Date('2026-05-02'),
    examDate: new Date('2026-06-08'),
    resultDate: new Date('2026-07-02'),
    conductingBody: 'MP Professional Examination Board (PEB)',
    category: 'Agriculture',
    mode: 'offline' as const,
    courses: ['B.Sc.', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'Mathematics/Biology or Elements of Agriculture'],
    pattern: 'Offline pen-paper test with 200 questions in 3 hours with no negative marking.',
    difficulty: 'Medium',
  },
  {
    examName: 'UPCATET 2026',
    slug: 'upcatet',
    fullName: 'UP Combined Agriculture and Technology Entrance Test',
    description: 'UPCATET is a state-level exam conducted for admission to various UG and PG agriculture courses in UP agricultural universities.',
    eligibility: 'Passed 10+2 with Agricultural Science / Physics, Chemistry & Biology / Mathematics.',
    applicationStartDate: new Date('2026-02-15'),
    applicationEndDate: new Date('2026-04-15'),
    examDate: new Date('2026-05-30'),
    resultDate: new Date('2026-06-25'),
    conductingBody: 'Chandra Shekhar Azad University of Agriculture & Technology',
    category: 'Agriculture',
    mode: 'offline' as const,
    courses: ['B.Sc.', 'Allied'],
    syllabus: ['General Studies', 'Physics', 'Chemistry', 'Mathematics / Biology / Agriculture domain subjects'],
    pattern: 'Pen and paper offline test containing 200 multiple-choice questions, duration 3 hours.',
    difficulty: 'Medium',
  },
  {
    examName: 'Bihar BCECE Agriculture 2026',
    slug: 'bihar-ugeac-agri',
    fullName: 'Bihar Combined Entrance Competitive Examination (Agriculture)',
    description: 'BCECE agriculture is the entrance exam for securing B.Sc. Agriculture and Horticulture seats in government colleges of Bihar.',
    eligibility: '10+2 passed with Physics, Chemistry and Biology/Maths/Agri subjects.',
    applicationStartDate: new Date('2026-04-12'),
    applicationEndDate: new Date('2026-05-12'),
    examDate: new Date('2026-06-15'),
    resultDate: new Date('2026-07-12'),
    conductingBody: 'Bihar Combined Entrance Competitive Examination Board (BCECEB)',
    category: 'Agriculture',
    mode: 'offline' as const,
    courses: ['B.Sc.', 'Allied'],
    syllabus: ['Physics', 'Chemistry', 'Biology / Mathematics / Agricultural Science'],
    pattern: 'Subject-wise papers of 100 questions each, duration 90 minutes per subject.',
    difficulty: 'Medium',
  },

  // ==========================================
  // DESIGN NEW EXAMS
  // ==========================================
  {
    examName: 'UCEED 2026',
    slug: 'uceed',
    fullName: 'Undergraduate Common Entrance Examination for Design',
    description: 'UCEED is conducted by IIT Bombay for admissions to the Bachelor of Design (B.Des) programs at IIT Bombay, IIT Delhi, IIT Guwahati, IIT Hyderabad, and IIITDM Jabalpur.',
    eligibility: 'Passed 10+2 or equivalent in any stream (Science, Commerce, or Arts & Humanities).',
    applicationStartDate: new Date('2025-10-01'),
    applicationEndDate: new Date('2025-11-10'),
    examDate: new Date('2026-01-18'),
    resultDate: new Date('2026-03-08'),
    conductingBody: 'Indian Institute of Technology (IIT) Bombay',
    category: 'Design',
    mode: 'offline' as const,
    courses: ['Allied', 'B.Arch'],
    syllabus: ['Visualization and Spatial Ability', 'Observation and Design Sensitivity', 'Analytical and Logical Reasoning', 'Drawing / Creativity'],
    pattern: 'Part-A (Computer-based test of 2 hours) and Part-B (Offline drawing test of 1 hour).',
    difficulty: 'Hard',
  },
  {
    examName: 'NID DAT 2026',
    slug: 'nid-dat',
    fullName: 'National Institute of Design - Design Aptitude Test',
    description: 'NID DAT is the national-level entrance exam conducted for admissions to Bachelor of Design (B.Des) courses across NID campuses.',
    eligibility: 'Passed or appearing in 10+2 in any stream from a recognized board.',
    applicationStartDate: new Date('2025-09-08'),
    applicationEndDate: new Date('2025-11-05'),
    examDate: new Date('2025-12-28'),
    resultDate: new Date('2026-02-15'),
    conductingBody: 'National Institute of Design (NID)',
    category: 'Design',
    mode: 'offline' as const,
    courses: ['Allied'],
    syllabus: ['NID DAT Prelims: Visual Analysis, Color and Composition, General mental ability', 'NID DAT Mains: Studio Test (Model making, material handling)'],
    pattern: 'Prelims (3-hour written exam containing objective and subjective design questions) followed by Mains (Studio test).',
    difficulty: 'Hard',
  },
  {
    examName: 'NIFT GCAT 2026',
    slug: 'nift-gcat',
    fullName: 'NIFT Entrance Examination (GAT & CAT)',
    description: 'NIFT entrance exam is conducted by NIFT for admissions to undergraduate design courses across 18 NIFT campuses.',
    eligibility: '10+2 from a recognized board. Maximum age limit is 24 years.',
    applicationStartDate: new Date('2025-11-01'),
    applicationEndDate: new Date('2025-12-31'),
    examDate: new Date('2026-02-05'),
    resultDate: new Date('2026-03-10'),
    conductingBody: 'National Institute of Fashion Technology (NIFT)',
    category: 'Design',
    mode: 'both' as const,
    courses: ['Allied'],
    syllabus: ['General Ability Test (Quantitative, Communication, English, GK)', 'Creative Ability Test (Intuitive ability, design sketch, concept illustration)'],
    pattern: 'Written exams: GAT (CBT mode) and CAT (Offline drawing mode), followed by a Situation Test.',
    difficulty: 'Medium to Hard',
  },
  {
    examName: 'SEED 2026',
    slug: 'seed-design',
    fullName: 'Symbiosis Entrance Exam for Design',
    description: 'SEED is conducted by Symbiosis International (Deemed University) for admission to the B.Des programs at Symbiosis Institute of Design.',
    eligibility: '10+2 or equivalent or 10+3 Diploma with minimum 50% marks from a recognized board.',
    applicationStartDate: new Date('2025-09-05'),
    applicationEndDate: new Date('2025-12-15'),
    examDate: new Date('2026-01-11'),
    resultDate: new Date('2026-01-22'),
    conductingBody: 'Symbiosis International (Deemed University)',
    category: 'Design',
    mode: 'online' as const,
    courses: ['Allied'],
    syllabus: ['Visualization', 'Observational Skills', 'Creative Thinking & Writing', 'Art & Craft History', 'Design Awareness'],
    pattern: '150-minute online test containing objective questions, followed by PRPI (Portfolio Review & Personal Interview).',
    difficulty: 'Medium',
  }
];

const defaultScholarships = [
  {
    scholarshipName: 'Aditya Birla Academy Scholarship',
    slug: 'aditya-birla',
    amount: '₹1,80,000 / Year',
    eligibility: 'Top 20 students in CLAT / CAT rank list, or top 50 in JEE Advanced',
    deadline: new Date('2026-09-30'),
    provider: 'Aditya Birla Group',
    type: 'Merit-Based',
    description: 'Academic tuition support for premier institute entrants.',
    details: 'This scholarship covers tuition and hostel fees for students joining premier law schools, IITs, and B-schools, honoring meritorious academic achievements throughout their course.',
  },
  {
    scholarshipName: 'Reliance Foundation Undergraduate Scholarship',
    slug: 'reliance-foundation',
    amount: 'Up to ₹2,00,000 / Year',
    eligibility: '1st-year UG students with family income < ₹15 Lakhs; Aptitude test clearance required',
    deadline: new Date('2026-10-15'),
    provider: 'Reliance Foundation',
    type: 'Need-cum-Merit',
    description: 'Support for deserving undergraduate students in engineering and IT fields.',
    details: 'Aims to support students in fields like engineering, medicine, and humanities. Awardees receive funding and access to mentoring and leadership workshops.',
  },
  {
    scholarshipName: "L'Oréal India For Young Women In Science",
    slug: 'loreal-science',
    amount: '₹2,50,000 Total',
    eligibility: 'Female students who passed 10+2 with PCB/PCM (min 85%) and family income < ₹6 LPA',
    deadline: new Date('2026-08-31'),
    provider: "L'Oréal India",
    type: 'Women in STEM',
    description: 'Financial aid for girls entering scientific careers.',
    details: 'Provides financial aid to young, passionate girls to pursue higher education in any scientific discipline at a recognized university in India.',
  },
];

const defaultBlogs = [
  {
    title: 'How to Crack CAT 2026: Strategy from a 100 Percentiler',
    slug: 'how-to-crack-cat',
    content: 'The Common Admission Test (CAT) is one of the most competitive exams globally, serving as the gateway to the elite Indian Institutes of Management (IIMs). In this detailed guide, Siddharth Sharma, who achieved a perfect 100 percentile in CAT 2025, shares his section-by-section preparation strategy, recommendations for mock tests, time management tips during the exam, and advice on handling pressure. Key highlights include: focusing on accuracy in Verbal Ability (VARC), building structured logic blocks for Data Interpretation (DILR), and selective question choice in Quant (QA).',
    excerpt: 'Cracking the Common Admission Test requires more than just knowing math formulas. It requires a mock strategy, section-wise timing, and mental resilience.',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=400&h=250&q=80',
    author: 'Siddharth Sharma',
    category: 'Exam Tips',
    tags: ['CAT', 'MBA', 'Exam Preparation'],
    readTime: '6 mins read',
    publishedAt: new Date('2026-06-12'),
  },
  {
    title: 'Top 5 College Destinations in India for Tech Graduates',
    slug: 'top-college-destinations-india',
    content: 'Choosing a college is not just about the institute itself; geography plays a massive role in internships, industry exposure, and placement opportunities. Bangalore (the Silicon Valley of India), Hyderabad, Pune, Mumbai, and Delhi NCR stand out as prime tech hubs. We break down the cost of living, presence of tech companies, local networking events, and the top engineering institutions in each of these cities to help you make an informed choice for your undergraduate studies.',
    excerpt: 'Explore why cities like Bangalore, Pune, and Hyderabad have become the absolute hotspots for technology studies and post-grad placements.',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=400&h=250&q=80',
    author: 'Priya Narang',
    category: 'Admission Updates',
    tags: ['Engineering', 'Placements', 'Cities'],
    readTime: '8 mins read',
    publishedAt: new Date('2026-06-05'),
  },
];

const defaultColleges = [
  {
    collegeName: 'Indian Institute of Management, Bangalore',
    name: 'Indian Institute of Management, Bangalore',
    slug: 'iim-bangalore',
    logo: 'iim-bangalore',
    banner: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&h=400&q=80',
    description: 'IIM Bangalore is a highly prestigious management school. Famed for its beautiful stone campus and exceptional academic rigour, it consistently produces elite leaders.',
    about: 'IIM Bangalore is a highly prestigious management school. Famed for its beautiful stone campus and exceptional academic rigour, it consistently produces elite leaders.',
    city: 'Bangalore',
    state: 'Karnataka',
    location: 'Karnataka, Bangalore',
    country: 'India',
    ranking: '#2 in India (NIRF MBA)',
    nirfRanking: 2,
    accreditation: 'EQUIS Accredited',
    establishedYear: 1973,
    fees: '₹23.0 Lakhs / Year',
    placementPercentage: 100,
    averagePackage: '34 LPA',
    highestPackage: '62 LPA',
    placements: '34 LPA Average',
    rating: 9.2,
    category: 'Management',
    website: 'https://www.iimb.ac.in',
    images: ['https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&h=400&q=80'],
    facilities: ['Case Rooms', 'Auditorium Complex', 'Executive Hostel'],
    infrastructure: ['Management Hub', 'Case Rooms', 'Auditorium Complex', 'Sports Center', 'Executive Hostel'],
    gallery: [
      'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=600&h=400&q=80',
    ],
    courses: [
      { name: 'MBA (PGP in Management)', fees: '₹11.5 Lakhs', seats: 480 },
      { name: 'Executive MBA (EPGP)', fees: '₹14.0 Lakhs', seats: 75 },
    ],
    placementDetails: [
      { company: 'McKinsey & Co', package: '₹38.5 LPA' },
      { company: 'Boston Consulting Group', package: '₹38.0 LPA' },
    ],
    scholarships: [
      { name: 'Financial Aid', criteria: 'Income < ₹8 Lakhs', amount: 'Up to 100% waiver' },
    ],
    hostels: [
      { type: 'Standard Room', sharing: 'Single', fees: '₹40,000 / Semester' },
    ],
    reviews: [
      { name: 'Deepak Rao', rating: 5, text: 'Case-study based learning is top-tier here.', date: '2026-03-24' },
    ],
    faq: [
      { q: 'Is CAT required?', a: 'Yes, CAT is mandatory for admission.' },
    ],
    totalOffers: 600,
    companyVisiting: 150,
    highestInternationalPackage: '82 LPA',
    phone: '+91 80 2699 3000',
    address: 'Bannerghatta Road, Bengaluru, Karnataka 560076',
    email: 'admissions@iimb.ac.in',
  },
  {
    collegeName: 'Symbiosis Institute of Business Management (SIBM), Pune',
    name: 'Symbiosis Institute of Business Management (SIBM), Pune',
    slug: 'symbiosis-pune',
    logo: 'symbiosis-pune',
    banner: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80',
    description: 'SIBM Pune is a premier B-School of India, renowned for its academic excellence, stellar placements, and vibrant student community.',
    about: 'Symbiosis Institute of Business Management, Pune is a premier constituent of SYMBIOSIS INTERNATIONAL (DEEMED UNIVERSITY) - SIU. Established in 1978, SIBM Pune is consistently ranked among the top B-Schools in the country.',
    city: 'Pune',
    state: 'Maharashtra',
    location: 'Maharashtra, Pune',
    country: 'India',
    ranking: '#7 in India (NIRF)',
    nirfRanking: 7,
    accreditation: 'NAAC A++',
    establishedYear: 1978,
    fees: '₹23.5 Lakhs / Year',
    placementPercentage: 98,
    averagePackage: '27 LPA',
    highestPackage: '36 LPA',
    placements: '27 LPA Average',
    rating: 8.8,
    category: 'Management',
    website: 'https://www.sibmpune.edu.in',
    images: ['https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80'],
    facilities: ['Modern Library', 'Seminar Halls', 'Student Hostels'],
    infrastructure: ['AC Classrooms', 'Auditorium', 'IT Infrastructure', 'Sports Arenas'],
    gallery: [
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80'
    ],
    courses: [
      { name: 'MBA (General Management)', fees: '₹12.0 Lakhs', seats: 180 },
      { name: 'MBA in Innovation and Entrepreneurship', fees: '₹10.5 Lakhs', seats: 60 }
    ],
    placementDetails: [
      { company: 'Accenture', package: '₹28 LPA' },
      { company: 'PwC', package: '₹26 LPA' }
    ],
    scholarships: [
      { name: 'SIU Sports Scholarship', criteria: 'State/National level players', amount: '50% Waiver' }
    ],
    hostels: [
      { type: 'Standard Room', sharing: 'Twin', fees: '₹1.1 Lakhs / Year' }
    ],
    reviews: [
      { name: 'Rohan Deshmukh', rating: 5, text: 'Amazing campus lifecycle and top-tier placements.', date: '2026-04-11' }
    ],
    faq: [
      { q: 'What is the entry exam?', a: 'SNAP is required for admission.' }
    ],
    totalOffers: 250,
    companyVisiting: 100,
    highestInternationalPackage: '39 LPA',
    phone: '+91 20 2811 6000',
    address: 'Senapati Bapat Rd, Pune, Maharashtra 411004',
    email: 'admissions@sibmpune.edu.in',
  },
  {
    collegeName: 'Graphic Era University, Dehradun',
    name: 'Graphic Era University, Dehradun',
    slug: 'graphic-era',
    logo: 'graphic-era',
    banner: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&h=400&q=80',
    description: 'Graphic Era (Deemed to be University) is a premier higher education institution in Dehradun, Uttarakhand, promoting top education and research.',
    about: 'Graphic Era University is a deemed university located in Dehradun, Uttarakhand. Established in 1993, it has grown to become a world-class academic hub for engineering and management programs.',
    city: 'Dehradun',
    state: 'Uttarakhand',
    location: 'Uttarakhand, Dehradun',
    country: 'India',
    ranking: '#8 in NIRF',
    nirfRanking: 55,
    accreditation: 'NAAC A+',
    establishedYear: 1993,
    fees: '₹8.0 Lakhs / Year',
    placementPercentage: 92,
    averagePackage: '6 LPA',
    highestPackage: '40 LPA',
    placements: '6 LPA Average',
    rating: 8.4,
    category: 'Engineering',
    website: 'https://www.geu.ac.in',
    images: ['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&h=400&q=80'],
    facilities: ['Advanced Computer Labs', 'Tech Incubation Cell', 'Central Gym'],
    infrastructure: ['AC Classrooms', 'Libraries', 'Hostels', 'Sports Fields'],
    gallery: [
      'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&h=400&q=80'
    ],
    courses: [
      { name: 'B.Tech in Computer Science', fees: '₹1.8 Lakhs', seats: 360 },
      { name: 'MBA', fees: '₹2.1 Lakhs', seats: 120 }
    ],
    placementDetails: [
      { company: 'Infosys', package: '₹8 LPA' },
      { company: 'Wipro', package: '₹6 LPA' }
    ],
    scholarships: [
      { name: 'Academic Merit Scholarship', criteria: 'Class 12 Marks > 90%', amount: '30% Waiver' }
    ],
    hostels: [
      { type: 'Standard Room', sharing: 'Twin', fees: '₹85,000 / Year' }
    ],
    reviews: [
      { name: 'Amit Negi', rating: 4, text: 'Great infrastructure, highly experienced faculty, and strong placements.', date: '2026-05-18' }
    ],
    faq: [
      { q: 'Is there a transport facility?', a: 'Yes, buses ply across major parts of Dehradun.' }
    ],
    totalOffers: 1800,
    companyVisiting: 200,
    highestInternationalPackage: '45 LPA',
    phone: '+91 135 264 3421',
    address: 'Bell Road, Clement Town, Dehradun, Uttarakhand 248002',
    email: 'admissions@geu.ac.in',
  },
  {
    collegeName: 'K R Mangalam University, (KRMU), Gurgaon',
    name: 'K R Mangalam University, (KRMU), Gurgaon',
    slug: 'kr-mangalam',
    logo: 'kr-mangalam',
    banner: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80',
    description: 'K R Mangalam University is a premier university located in Gurgaon, offering dynamic undergraduate and postgraduate programs with advanced corporate training setups.',
    about: 'K R Mangalam University is a premier university located in Gurgaon, offering dynamic undergraduate and postgraduate programs with advanced corporate training setups.',
    city: 'Gurgaon',
    state: 'Haryana',
    location: 'Haryana, Gurgaon',
    country: 'India',
    ranking: '#8 in India (NIRF)',
    nirfRanking: 75,
    accreditation: 'UGC Recognized',
    establishedYear: 2013,
    fees: '₹2.10 Lakhs / Year',
    placementPercentage: 85,
    averagePackage: '12 LPA',
    highestPackage: '57 LPA',
    placements: '12 LPA Average',
    rating: 8.0,
    category: 'Management',
    website: 'https://www.krmangalam.edu.in',
    images: ['https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80'],
    facilities: ['AC Classrooms', 'Moot Court', 'Innovation Cell'],
    infrastructure: ['AC Classrooms', 'Moot Court', 'Central Library', 'Innovation Cell'],
    gallery: [
      'https://images.unsplash.com/photo-1498243691581-b145c3f54a5c?auto=format&fit=crop&w=600&h=400&q=80',
    ],
    courses: [
      { name: 'B.Tech in Computer Science', fees: '₹2.10 Lakhs', seats: 150 },
      { name: 'MBA (PGP in Management)', fees: '₹3.20 Lakhs', seats: 120 },
    ],
    placementDetails: [
      { company: 'Amazon', package: '₹36.0 LPA' },
      { company: 'HCL', package: '₹6.0 LPA' },
    ],
    scholarships: [
      { name: 'KRMU Scholarship', criteria: 'Class 12 Marks > 90%', amount: '50% Waiver' },
    ],
    hostels: [
      { type: 'AC Double Sharing', sharing: 'Twin', fees: '₹1.2 Lakhs / Year' },
    ],
    reviews: [
      { name: 'Amit Roy', rating: 4, text: 'Great infrastructure and good corporate linkages.', date: '2026-04-10' },
    ],
    faq: [
      { q: 'Is there a transport service?', a: 'Yes, buses connect all parts of NCR.' },
    ],
    totalOffers: 1200,
    companyVisiting: 180,
    highestInternationalPackage: '57 LPA',
    phone: '+91 11 4888 8888',
    address: 'Sohna Road, Gurugram, Haryana 122103',
    email: 'admissions@krmangalam.edu.in',
  },
  {
    collegeName: 'Indian Institute of Space Science and Technology (IIST)',
    name: 'Indian Institute of Space Science and Technology',
    slug: 'iist-thiruvananthapuram',
    logo: 'great-lakes',
    banner: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80',
    description: 'IIST is Asias first Space University, established by ISRO in Thiruvananthapuram, Kerala, to offer high-quality space science education.',
    about: 'Indian Institute of Space Science and Technology (IIST), located at Thiruvananthapuram, Kerala, is a government-aided institute and deemed university for space science research and applications.',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    location: 'Kerala, Thiruvananthapuram',
    country: 'India',
    ranking: '#9 in NIRF',
    nirfRanking: 28,
    accreditation: 'ISRO Sponsored',
    establishedYear: 2007,
    fees: '₹1.44 Lakhs / Year',
    placementPercentage: 90,
    averagePackage: '8 LPA',
    highestPackage: '12 LPA',
    placements: '8 LPA Average',
    rating: 9.2,
    category: 'Engineering',
    website: 'https://www.iist.ac.in',
    images: ['https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80'],
    facilities: ['Aerodynamics Lab', 'Astronomical Observatory', 'Satellite Ground Station'],
    infrastructure: ['Advanced Labs', 'Observatory', 'Computational Facilities', 'Library', 'Hostels'],
    gallery: [
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80'
    ],
    courses: [
      { name: 'B.Tech in Aerospace Engineering', fees: '₹1.2 Lakhs', seats: 60 },
      { name: 'M.Tech in Space Science', fees: '₹1.44 Lakhs', seats: 20 }
    ],
    placementDetails: [
      { company: 'ISRO', package: '₹10 LPA' },
      { company: 'Microsoft', package: '₹12 LPA' }
    ],
    scholarships: [
      { name: 'ISRO Assistantship', criteria: 'CGPA > 7.5', amount: 'Full Waiver' }
    ],
    hostels: [
      { type: 'Standard Room', sharing: 'Twin', fees: '₹35,000 / Year' }
    ],
    reviews: [
      { name: 'Arjun Nair', rating: 5, text: 'Unmatched research opportunities and direct ISRO recruitment route.', date: '2026-03-12' }
    ],
    faq: [
      { q: 'Is admission direct to ISRO possible?', a: 'Yes, students meeting the required CGPA threshold are directly absorbed by ISRO.' }
    ],
    totalOffers: 150,
    companyVisiting: 40,
    highestInternationalPackage: '16 LPA',
    phone: '+91 471 256 8400',
    address: 'Valiamala Road, Thiruvananthapuram, Kerala 695547',
    email: 'admissions@iist.ac.in',
  },
  {
    collegeName: 'FMS Delhi: Faculty of Management Studies, Delhi',
    name: 'FMS Delhi: Faculty of Management Studies, Delhi',
    slug: 'fms-delhi',
    logo: 'iit-bombay',
    banner: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&h=400&q=80',
    description: 'Faculty of Management Studies, Delhi is one of the oldest and most prestigious business schools in India, famous for its ROI.',
    about: 'Faculty of Management Studies (FMS), Delhi, established in 1954 under the aegis of the University of Delhi, is renowned for its academic excellence and high return on investment (ROI).',
    city: 'Delhi',
    state: 'Delhi',
    location: 'Delhi, Delhi',
    country: 'India',
    ranking: '#10 in NIRF',
    nirfRanking: 10,
    accreditation: 'Delhi University Affiliated',
    establishedYear: 1954,
    fees: '₹2.0 Lakhs / Year',
    placementPercentage: 100,
    averagePackage: '35 LPA',
    highestPackage: '1.23 CR',
    placements: '35 LPA Average',
    rating: 8.9,
    category: 'Management',
    website: 'http://fms.edu',
    images: ['https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&h=400&q=80'],
    facilities: ['DU Central Library', 'Seminar Rooms', 'Corporate Relations Cell'],
    infrastructure: ['Management Classrooms', 'Library', 'IT Labs'],
    gallery: [
      'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=600&h=400&q=80'
    ],
    courses: [
      { name: 'MBA Full Time', fees: '₹2.0 Lakhs', seats: 290 },
      { name: 'MBA Executive', fees: '₹1.5 Lakhs', seats: 150 }
    ],
    placementDetails: [
      { company: 'McKinsey', package: '₹38 LPA' },
      { company: 'Google', package: '₹42 LPA' }
    ],
    scholarships: [
      { name: 'OPJEMS Scholarship', criteria: 'Merit List Top Performers', amount: '₹1.5 Lakhs' }
    ],
    hostels: [
      { type: 'DU Hostels', sharing: 'Twin', fees: '₹12,000 / Year' }
    ],
    reviews: [
      { name: 'Vikram Singh', rating: 5, text: 'Stellar placements with practically zero fees. Best ROI in the country.', date: '2026-05-10' }
    ],
    faq: [
      { q: 'Is CAT required?', a: 'Yes, CAT is the primary entrance exam.' }
    ],
    totalOffers: 300,
    companyVisiting: 120,
    highestInternationalPackage: '1.23 CR',
    phone: '+91 11 2766 6382',
    address: 'Malka Ganj, Delhi 110007',
    email: 'admissions@fms.edu',
  },
  {
    collegeName: 'MIT World Peace University, Pune',
    name: 'MIT World Peace University, Pune',
    slug: 'mit-wpu',
    logo: 'mit-wpu',
    banner: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80',
    description: 'MIT World Peace University (MIT-WPU), prevalently known as MIT-WPU Pune, is one of the main confidential designing and board establishments in India, boasting global standards of learning.',
    about: 'MIT World Peace University (MIT-WPU) is a state-private university located in Kothrud, Pune. Established in 1983 as Maharashtra Institute of Technology (MIT), it has evolved into a premier tech and research hub with an accentuation on academic rigor and values-based holistic education.',
    city: 'Pune',
    state: 'Maharashtra',
    location: 'Pune, Maharashtra',
    country: 'India',
    ranking: 'AICTE, UGC, BCI Accredited',
    nirfRanking: 80,
    accreditation: 'AICTE, UGC, BCI',
    establishedYear: 1983,
    fees: '₹3.5 - 5 Lakhs / Year',
    placementPercentage: 75,
    averagePackage: '7 LPA',
    highestPackage: '51.36 LPA',
    placements: '7 LPA Average',
    rating: 7.8,
    category: 'Engineering',
    website: 'https://mitwpu.edu.in',
    images: ['https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80'],
    facilities: ['World Peace Dome', 'Robotics Innovation Lab', 'Olympics-size Track'],
    infrastructure: ['AC Classrooms', 'World Peace Dome', 'Robotics Hub', 'Sports Arenas', 'Hostel Mess'],
    gallery: [
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=600&h=400&q=80',
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&h=400&q=80'
    ],
    courses: [
      { name: 'B.Tech in Computer Science & Engineering', fees: '₹3.5 Lakhs / Year', seats: 240 },
      { name: 'MBA (General Management)', fees: '₹4.8 Lakhs / Year', seats: 180 },
      { name: 'BBA in International Business', fees: '₹2.8 Lakhs / Year', seats: 120 }
    ],
    placementDetails: [
      { company: 'Flipkart', package: '₹22.5 LPA' },
      { company: 'Infosys', package: '₹7.5 LPA' },
      { company: 'Cybage Software', package: '₹6.2 LPA' },
      { company: 'Credit Suisse', package: '₹14.8 LPA' },
      { company: 'Cognizant', package: '₹8.0 LPA' },
      { company: 'Amazon', package: '₹32.0 LPA' },
      { company: 'Kotak Mahindra Bank', package: '₹11.0 LPA' },
      { company: 'TATA Motors', package: '₹9.5 LPA' },
      { company: 'KPMG', package: '₹12.0 LPA' },
      { company: 'IBM', package: '₹10.5 LPA' },
      { company: 'Aditya Birla Group', package: '₹18.0 LPA' },
      { company: 'Deloitte', package: '₹15.0 LPA' },
      { company: 'Tech Mahindra', package: '₹6.5 LPA' },
      { company: 'Capgemini', package: '₹8.2 LPA' },
      { company: 'Microsoft', package: '₹44.0 LPA' },
      { company: 'Whirlpool', package: '₹8.8 LPA' },
      { company: 'Accenture', package: '₹9.0 LPA' },
      { company: 'Wipro', package: '₹7.0 LPA' },
      { company: 'HDFC Bank', package: '₹12.5 LPA' },
      { company: 'TCS', package: '₹6.8 LPA' }
    ],
    scholarships: [
      { name: 'Dr. Vishwanath Karad Merit Scholarship', criteria: 'JEE > 97 percentile or Boards > 95%', amount: '100% Tuition Waiver' },
      { name: 'MIT-WPU Sports Achievement Award', criteria: 'National level medalists', amount: '50% Waiver' }
    ],
    hostels: [
      { type: 'Premium Hostel Wing', sharing: 'Twin', fees: '₹1.5 Lakhs / Year' },
      { type: 'Standard Wing', sharing: 'Triple', fees: '₹1.2 Lakhs / Year' }
    ],
    reviews: [
      { name: 'Rahul Joshi', rating: 5, text: 'Awesome campus infrastructure and very cooperative faculty.', date: '2026-05-12' },
      { name: 'Sneha Patil', rating: 4, text: 'Placements are very good. Companies like Amazon, Microsoft, and Infosys visit regularly.', date: '2026-04-20' }
    ],
    faq: [
      { q: 'Is there direct admission in MIT WPU?', a: 'Admissions are strictly merit-based, considering exam scores like JEE, SNAP, MHT-CET, or MIT-WPU CET.' },
      { q: 'Is hostel mandatory for all students?', a: 'No, hostel accommodation is optional.' }
    ],
    totalOffers: 2214,
    companyVisiting: 235,
    highestInternationalPackage: '37.26 LPA',
    phone: '+91 7773045555',
    address: 'S.No.124, Paud Road, Kothrud Pune - 411038 Maharashtra, India',
    email: 'admissions@mitwpu.edu.in',
  },
  {
    collegeName: 'Indian Institute of Technology Bombay',
    name: 'Indian Institute of Technology Bombay',
    slug: 'iit-bombay',
    logo: 'iit-bombay',
    banner: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
    description: 'IIT Bombay is a top-ranked engineering institution globally. It offers advanced engineering research, innovation cells, and high-impact technology placements.',
    about: 'The Indian Institute of Technology Bombay is a premier public research university and engineering institution located in Powai, Mumbai. Established in 1958, it is globally recognized for its science and engineering leadership.',
    city: 'Mumbai',
    state: 'Maharashtra',
    location: 'Mumbai, Maharashtra',
    country: 'India',
    ranking: '#3 in India (NIRF Overall)',
    nirfRanking: 3,
    accreditation: 'Institute of Eminence',
    establishedYear: 1958,
    fees: '₹2.2 Lakhs / Year',
    placementPercentage: 99,
    averagePackage: '21.8 LPA',
    highestPackage: '1.68 CR',
    placements: '21.8 LPA Average',
    rating: 9.6,
    category: 'Engineering',
    website: 'https://www.iitb.ac.in',
    images: ['https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80'],
    facilities: ['Nanotechnology Center', 'Aerospace Testing Tunnel', 'Convocation Hall'],
    infrastructure: ['Supercomputing Lab', 'High-tech Classrooms', 'Sports Complex', 'Lakeside Hostels'],
    gallery: [
      'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80'
    ],
    courses: [
      { name: 'B.Tech in Computer Science and Engineering', fees: '₹2.2 Lakhs / Year', seats: 120 },
      { name: 'B.Tech in Electrical Engineering', fees: '₹2.2 Lakhs / Year', seats: 100 }
    ],
    placementDetails: [
      { company: 'Google Inc', package: '₹1.68 CPA' },
      { company: 'Microsoft', package: '₹48 LPA' }
    ],
    scholarships: [
      { name: 'IITB Merit-cum-Means', criteria: 'Parental Income < ₹4.5 Lakhs', amount: 'Full Tuition Waiver' }
    ],
    hostels: [
      { type: 'Hostel 1 to 18 (Powai)', sharing: 'Single', fees: '₹25,000 / Year' }
    ],
    reviews: [
      { name: 'Karan Malhotra', rating: 5, text: 'Incredible faculty, campus events like Mood Indigo are amazing, and placement stats speak for themselves.', date: '2026-05-02' }
    ],
    faq: [
      { q: 'What is the entry exam?', a: 'JEE Advanced is mandatory for B.Tech admission.' }
    ],
    totalOffers: 1650,
    companyVisiting: 350,
    highestInternationalPackage: '1.68 CR',
    phone: '+91 22 2572 2545',
    address: 'Main Gate Rd, IIT Area, Powai, Mumbai, Maharashtra 400076',
    email: 'admissions@iitb.ac.in',
  },
  {
    collegeName: 'Sharda University Noida',
    name: 'Sharda University Noida',
    slug: 'sharda-university',
    logo: 'sharda-university',
    banner: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
    description: 'Sharda University Noida is a premier global private university in Greater Noida, NCR, offering premium campus placements and diverse programs.',
    about: 'Sharda University is a private university in Greater Noida, Uttar Pradesh, established in 2009. The university has students from 85+ countries and offers multi-disciplinary programs.',
    city: 'Noida',
    state: 'Uttar Pradesh',
    location: 'Noida, Uttar Pradesh',
    country: 'India',
    ranking: 'NAAC A+ Accredited',
    nirfRanking: 87,
    accreditation: 'NAAC A+',
    establishedYear: 2009,
    fees: '₹2.1 Lakhs / Year',
    placementPercentage: 91,
    averagePackage: '6.5 LPA',
    highestPackage: '52.0 LPA',
    placements: '6.5 LPA Average',
    rating: 7.9,
    category: 'Engineering',
    website: 'https://www.sharda.ac.in',
    images: ['https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80'],
    facilities: ['Sharda Hospital', 'Advanced Labs', 'Moot Court'],
    infrastructure: ['AC Classrooms', 'Central Library', 'Cafeterias', 'Multi-sport Complex'],
    gallery: [
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80'
    ],
    courses: [
      { name: 'B.Tech in Computer Science', fees: '₹2.1 Lakhs', seats: 300 },
      { name: 'MBA in Marketing', fees: '₹3.5 Lakhs', seats: 120 }
    ],
    placementDetails: [
      { company: 'Amazon', package: '₹18 LPA' },
      { company: 'TCS', package: '₹6.5 LPA' }
    ],
    scholarships: [
      { name: 'Sharda Scholarship Plan', criteria: 'JEE Rank < 25000', amount: '80% Tuition Waiver' }
    ],
    hostels: [
      { type: 'AC Room - Twin Sharing', sharing: 'Twin', fees: '₹1.15 Lakhs / Year' }
    ],
    reviews: [
      { name: 'Rohan Sharma', rating: 4, text: 'Great multicultural exposure and very decent placements.', date: '2026-04-18' }
    ],
    faq: [
      { q: 'Is there any registration fee?', a: 'Yes, a standard university application fee applies.' }
    ],
    totalOffers: 4500,
    companyVisiting: 150,
    highestInternationalPackage: '35 LPA',
    phone: '+91 120 457 0000',
    address: 'Plot No. 32-34, Knowledge Park III, Greater Noida, Uttar Pradesh 201306',
    email: 'admissions@sharda.ac.in',
  },
  {
    collegeName: 'Birla Institute of Technology & Science Pilani',
    name: 'Birla Institute of Technology & Science Pilani',
    slug: 'bits-pilani',
    logo: 'bits-pilani',
    banner: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=1200&q=80',
    description: 'BITS Pilani is a highly premier science and engineering university. Famous for its flexible "no attendance" policy and strong startup culture.',
    about: 'Birla Institute of Technology & Science, Pilani (BITS Pilani) is a deemed university in Pilani, Rajasthan. Established in 1964, it is widely recognized as one of the best engineering colleges in India with additional campuses in Goa, Hyderabad, and Dubai.',
    city: 'Pilani',
    state: 'Rajasthan',
    location: 'Pilani, Rajasthan',
    country: 'India',
    ranking: '#20 in India (NIRF Overall)',
    nirfRanking: 20,
    accreditation: 'NAAC A Grade',
    establishedYear: 1964,
    fees: '₹4.5 Lakhs / Year',
    placementPercentage: 100,
    averagePackage: '30.37 LPA',
    highestPackage: '60.75 LPA',
    placements: '30.37 LPA Average',
    rating: 9.4,
    category: 'Engineering',
    website: 'https://www.bits-pilani.ac.in',
    images: ['https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=1200&q=80'],
    facilities: ['BITS Clock Tower', 'Practice School System', 'Student Activity Center'],
    infrastructure: ['AC Laboratories', 'Libraries', 'Playgrounds', 'Hostels'],
    gallery: [
      'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=1200&q=80'
    ],
    courses: [
      { name: 'B.E. in Computer Science', fees: '₹4.5 Lakhs / Year', seats: 120 },
      { name: 'B.E. in Mechanical Engineering', fees: '₹4.5 Lakhs / Year', seats: 100 }
    ],
    placementDetails: [
      { company: 'Uber Technologies', package: '₹60.75 LPA' },
      { company: 'Apple Inc', package: '₹48.0 LPA' }
    ],
    scholarships: [
      { name: 'BITS Merit-cum-Need', criteria: 'CGPA > 8.0', amount: '80% Fee Waiver' }
    ],
    hostels: [
      { type: 'Standard Single Room', sharing: 'Single', fees: '₹55,000 / Year' }
    ],
    reviews: [
      { name: 'Ananya Goel', rating: 5, text: 'No attendance policy and the Practice School internship systems are absolute game-changers.', date: '2026-05-15' }
    ],
    faq: [
      { q: 'Is BITSAT mandatory?', a: 'Yes, BITSAT scores are strictly used for engineering admissions.' }
    ],
    totalOffers: 1200,
    companyVisiting: 400,
    highestInternationalPackage: '1.2 CPA',
    phone: '+91 1596 245 073',
    address: 'Vidya Vihar, Pilani, Rajasthan 333031',
    email: 'admissions@pilani.bits-pilani.ac.in',
  },
  {
    collegeName: 'NMIMS Deemed-to-be-University Mumbai',
    name: 'NMIMS Deemed-to-be-University Mumbai',
    slug: 'nmims-mumbai',
    logo: 'nmims-mumbai',
    banner: 'https://images.unsplash.com/photo-1527891751199-7225231a68dd?auto=format&fit=crop&w=1200&q=80',
    description: 'NMIMS Mumbai is a top-tier business university. Renowned for its Core MBA programs, premium infrastructure, and corporate integrations.',
    about: 'SVKMs NMIMS (Narsee Monjee Institute of Management Studies) is a premier deemed-to-be university established in 1981 in Mumbai. It has expanded into a multi-campus institution offering high-quality management training.',
    city: 'Mumbai',
    state: 'Maharashtra',
    location: 'Mumbai, Maharashtra',
    country: 'India',
    ranking: '#21 in India (NIRF Management)',
    nirfRanking: 21,
    accreditation: 'AACSB Accredited',
    establishedYear: 1981,
    fees: '₹10.5 Lakhs / Year',
    placementPercentage: 98,
    averagePackage: '23.07 LPA',
    highestPackage: '67.80 LPA',
    placements: '23.07 LPA Average',
    rating: 8.7,
    category: 'Management',
    website: 'https://www.nmims.edu',
    images: ['https://images.unsplash.com/photo-1527891751199-7225231a68dd?auto=format&fit=crop&w=1200&q=80'],
    facilities: ['Bloomberg Terminal Labs', 'Conference Halls', 'Digital Classrooms'],
    infrastructure: ['Digital Classrooms', 'Bloomberg Terminals', 'Central Library', 'Premium Cafeterias'],
    gallery: [
      'https://images.unsplash.com/photo-1527891751199-7225231a68dd?auto=format&fit=crop&w=1200&q=80'
    ],
    courses: [
      { name: 'MBA Core', fees: '₹10.5 Lakhs / Year', seats: 600 },
      { name: 'BBA in Management', fees: '₹3.2 Lakhs / Year', seats: 360 }
    ],
    placementDetails: [
      { company: 'Goldman Sachs', package: '₹28 LPA' },
      { company: 'JPMorgan Chase', package: '₹26 LPA' }
    ],
    scholarships: [
      { name: 'SVKM Scholarship scheme', criteria: 'Family Income < ₹6 Lakhs', amount: '30% Fee Support' }
    ],
    hostels: [
      { type: 'Off-campus Premium AC Housing', sharing: 'Twin', fees: '₹2.8 Lakhs / Year' }
    ],
    reviews: [
      { name: 'Siddharth Jain', rating: 5, text: 'Awesome corporate connections. Virtually every top consulting firm visits here.', date: '2026-05-19' }
    ],
    faq: [
      { q: 'Is NMAT required?', a: 'Yes, NMAT by GMAC is the mandatory exam for MBA admission.' }
    ],
    totalOffers: 800,
    companyVisiting: 220,
    highestInternationalPackage: '67.8 LPA',
    phone: '+91 22 4235 5555',
    address: 'V. L. Mehta Road, Vile Parle West, Mumbai, Maharashtra 400056',
    email: 'admissions@nmims.edu',
  },
  {
    collegeName: 'Lovely Professional University Punjab',
    name: 'Lovely Professional University Punjab',
    slug: 'lpu-punjab',
    logo: 'lpu-punjab',
    banner: 'https://images.unsplash.com/photo-1607237138185-eedd996c5c0c?auto=format&fit=crop&w=1200&q=80',
    description: 'Lovely Professional University (LPU) is a massive private university in Punjab, offering a giant campus and a record number of placements.',
    about: 'Lovely Professional University is a private university located in Chaheru, Phagwara, Punjab. Established in 2005, it features a huge 600+ acre campus and has thousands of domestic and international students.',
    city: 'Phagwara',
    state: 'Punjab',
    location: 'Phagwara, Punjab',
    country: 'India',
    ranking: '#38 in India (NIRF Overall)',
    nirfRanking: 38,
    accreditation: 'UGC & COA Approved',
    establishedYear: 2005,
    fees: '₹2.4 Lakhs / Year',
    placementPercentage: 95,
    averagePackage: '7.8 LPA',
    highestPackage: '64.0 LPA',
    placements: '7.8 LPA Average',
    rating: 8.1,
    category: 'Engineering',
    website: 'https://www.lpu.in',
    images: ['https://images.unsplash.com/photo-1607237138185-eedd996c5c0c?auto=format&fit=crop&w=1200&q=80'],
    facilities: ['LPU Shopping Mall', 'Indoor Stadium', 'Uni-Hospital'],
    infrastructure: ['AC Classrooms', 'Massive Central Library', 'Uni-Mall', 'Auditoriums', 'Sports Complex'],
    gallery: [
      'https://images.unsplash.com/photo-1607237138185-eedd996c5c0c?auto=format&fit=crop&w=1200&q=80'
    ],
    courses: [
      { name: 'B.Tech in Computer Science', fees: '₹2.4 Lakhs', seats: 1200 },
      { name: 'MBA (Executive)', fees: '₹3.6 Lakhs', seats: 240 }
    ],
    placementDetails: [
      { company: 'Cognizant', package: '₹8.5 LPA' },
      { company: 'Capgemini', package: '₹7.2 LPA' }
    ],
    scholarships: [
      { name: 'LPU NEST Scholarship', criteria: 'LPUNEST top ranks', amount: 'Up to 50% tuition support' }
    ],
    hostels: [
      { type: 'AC Single Room', sharing: 'Single', fees: '₹95,000 / Year' }
    ],
    reviews: [
      { name: 'Ritesh Kumar', rating: 4, text: 'Massive infrastructure, endless events, and very high placement rates for CSE graduates.', date: '2026-05-14' }
    ],
    faq: [
      { q: 'Is LPUNEST mandatory?', a: 'Yes, it is the primary route for engineering admissions and scholarships.' }
    ],
    totalOffers: 6000,
    companyVisiting: 2225,
    highestInternationalPackage: '64 LPA',
    phone: '+91 1824 517000',
    address: 'Jalandhar - Delhi, G.T. Road, Phagwara, Punjab 144411',
    email: 'admissions@lpu.co.in',
  }
];

export const seedDB = async (shouldExit: boolean = true) => {
  try {
    if (mongoose.connection.readyState === 0) {
      console.log('Connecting to database...');
      await mongoose.connect(MONGODB_URI);
      console.log('Connected to MongoDB.');
    } else {
      console.log('Using existing MongoDB connection.');
    }

    // Clear existing collections
    console.log('Clearing old collections...');
    await Promise.all([
      User.deleteMany({}),
      College.deleteMany({}),
      Course.deleteMany({}),
      Exam.deleteMany({}),
      Scholarship.deleteMany({}),
      Blog.deleteMany({}),
      Application.deleteMany({}),
      SavedCollege.deleteMany({}),
      ComparedCollege.deleteMany({}),
    ]);
    console.log('Database cleared.');

    // Seed Courses
    console.log('Seeding courses...');
    const insertedCourses = await Course.insertMany(defaultCourses);
    console.log(`Seeded ${insertedCourses.length} courses.`);

    // Seed Exams
    console.log('Seeding entrance exams...');
    const insertedExams = await Exam.insertMany(defaultExams);
    console.log(`Seeded ${insertedExams.length} exams.`);

    // Seed Scholarships
    console.log('Seeding scholarships...');
    const insertedScholarships = await Scholarship.insertMany(defaultScholarships);
    console.log(`Seeded ${insertedScholarships.length} scholarships.`);

    // Seed Blogs
    console.log('Seeding blogs...');
    const insertedBlogs = await Blog.insertMany(defaultBlogs);
    console.log(`Seeded ${insertedBlogs.length} blogs.`);

    // Seed Colleges
    console.log('Seeding colleges...');
    const insertedColleges = await College.insertMany(defaultColleges);
    console.log(`Seeded ${insertedColleges.length} colleges.`);

    // Seed Users (Student and Admin)
    console.log('Seeding users...');
    const admin = new User({
      fullName: 'Aruna-Nand EdTech Admin',
      email: 'admin@arunanandedtech.org',
      phone: '9999999999',
      password: 'AdminPassword@123',
      role: 'admin',
      isVerified: true,
      city: 'Bangalore',
      state: 'Karnataka',
    });

    const student = new User({
      fullName: 'Karan Sharma',
      email: 'student@arunanandedtech.org',
      phone: '8888888888',
      password: 'StudentPassword@123',
      role: 'student',
      isVerified: true,
      city: 'Delhi',
      state: 'Delhi',
    });

    await admin.save();
    await student.save();
    console.log('Users seeded successfully. Credentials:');
    console.log('- Admin: admin@arunanandedtech.org / AdminPassword@123');
    console.log('- Student: student@arunanandedtech.org / StudentPassword@123');

    // Create a mock application
    console.log('Creating a mock application...');
    await Application.create({
      userId: student._id,
      collegeId: insertedColleges[0]._id, // IIM Bangalore
      courseId: insertedCourses[0]._id, // B.Tech
      applicationStatus: 'submitted',
    });
    console.log('Mock application created.');

    console.log('Database seeding process completed successfully!');
    if (shouldExit) {
      process.exit(0);
    }
  } catch (error) {
    console.error('Seeding engine encountered an error:', error);
    if (shouldExit) {
      process.exit(1);
    } else {
      throw error;
    }
  }
};

if (require.main === module) {
  seedDB(true);
}
